import type { Metadata } from "next";
import { Geist, Geist_Mono,Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  subsets: ['latin'],
  weight: ['400', '700'], // add weights you need
  variable: '--font-cairo', // optional CSS variable for custom properties
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`bg-[#1A1A1A] ${cairo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
